### ISSUE TITLE
Consider renaming repo to jekyll-date_logic

### ISSUE THREAD

**Issue by gregoryjscott** [cityoffortworth/jekyll-date_logic#1]
This will align it to [Ruby gem naming standards](http://guides.rubygems.org/name-your-gem/). Also, if you give me push access then I'll merge [my work](https://github.com/gregoryjscott/jekyll-date_logic).

**Comment by bechatman** [comment]
Sorry... forgot to do that. You should have access now.

**Comment by gregoryjscott** [comment]
I pushed my work to this repo.
